### ISSUE TITLE
Missing Text

### ISSUE THREAD

**Issue by CdysRed** [gutieashl/SpellResearchAlternateTomePatcher#2] opened 2022-02-14 05:05 UTC
Sorry to bother you with this, it's probably something I missed on my end.
So, the problem is two-fold...
For one - if I try to play an existing save after adding the synthesis patch, opening any container with a spellbook in it leads to immediate ctd. Not a big deal, I would have no problems starting over.
But then there's the other thing - if I try it on a new save, all the spellbooks look like this: https://ibb.co/s18Lg4W
Couple things I could note is that I use "Natural typefaces of skyrim" and bashed patch that loads before synthesis.esp
Patched spellbook mods are "Mysticism" from https://www.nexusmods.com/skyrimspecialedition/mods/32706 (one from patch compendium redux doesn't work properly)
And "LostGrimoire" with "DawnguardArsenal" from https://www.nexusmods.com/skyrimspecialedition/mods/61177 (loose version for the psc files)
Reply at your leisure. I will try to figure it out on my own in the meantime.

**Comment by gutieashl** [comment] 2022-02-14 06:52
So far I can't reproduce this, tried all those mods together and it seems to work fine.

It really shouldn't CTD even if you use an existing game. If you did something like recreate a merged synthesis patch with several patchers, that might screw things up. I would recommend creating a new patch group in synthesis and creating a patch with only this.

Check that it is crashing due to this patcher by checking the crash log output of [.Net Script Framework](https://www.nexusmods.com/skyrimspecialedition/mods/21294).

The only other reason I can think of that it may CTD is when the teaches flag is set, but the teaches spell is cleared. This happens with older versions of mutagen, so make sure your mutagen is up to date, and check the flags in xEdit.

As for the font problem? maybe try disabling all the font/color flags. It kind of seems like you're missing the (vanilla) fonts. Is Font Overhaul working correctly?

If you are still having problems, Ill need to see a screenshot of an affected book record with all its overrides in xEdit (after you load your full load order), as well as the raw text in the description element of the winning override of the book record (copy it).

**Comment by CdysRed** [comment] 2022-02-14 07:48
Right, so what I did since posting was reinstall the patch on a new group, though it was the only one in the group the first time. I never even used synthesis before this.
Then I unchecked using font colour in patcher settings for all books.
Font overhaul seems to be completely unrelated, as it replaces vanilla font and the results after disabling it are the same. Every other non-spell book reads just fine.
Still no dice.
The latest logs in Data/NetScriptFramework/Crash are from over a year ago. I had completely different load order then. Ctd in existing save may be caused by the fact that at some point I had "Challenging spell learning" installed there. I honestly can live without it, it wasn't a very old save.
Screenshots of one of the spellbooks attached, not sure if that's what you wanted,  sorry:
![Capture1](https://user-images.githubusercontent.com/99632037/153820712-0279c983-6a5e-42c7-8fc1-5565153f2b0a.PNG)
![Capture2](https://user-images.githubusercontent.com/99632037/153820741-5d57e4be-5822-434e-a0e4-692a7f7a442b.PNG)
Raw desc text from synthesis.esp:
<br><br><p align="center"><font face=''><font size='40'></font>Candlelight<br><br></p>[pagebreak]<br><br><p align="left"><font face=''><font size='40'></font>A  spell of the  school, cast</font></p>
P.S. First time I've tried installing the patch it would error when using "Latest" for both mutagen and synthesis, and I only have gotten it to work by setting "Match" for both, resulting in 0.35.1 with 0.20.6 combo. Hours later now, I've set both to latest and it worked just fine. Still the same result, sadly.

P.S.S Lost grimoire AND Mysticism non-vanilla spell books work just fine (yay, progress). It appears only vanilla books edited by mysticism have the squares problem, perhaps I should try to install the patch without skyrim.esm? Not sure if mysticism touches all of vanilla spells, most likely not.

**Comment by gutieashl** [comment] 2022-02-14 10:50
looks like you didnt set a font, in the settings, you have to set the fonts to one of the fonts listed in the description.

**Comment by CdysRed** [comment] 2022-02-14 11:08
I'm using $SkyrimBooks for all.
It works fine for mod added skillbooks, as I now discovered in my previous post. Just mod-edited vanilla books have the issue.
Unless you mean something else.

**Comment by gutieashl** [comment] 2022-02-14 11:12
Looks like it didn't process vanilla skyrim, do you have a valid vanilla skyrim spell research patch? Can you look into the psc and make sure it actually has archetypes and looks correct.

**Comment by CdysRed** [comment] 2022-02-14 11:15
This is my skyrim psc: https://mega.nz/file/Ubx1kapS#skhGBwGarELVQhLD7_eh2W_zGoSRKXw5pSNzCeZWmfI
I've never edited or even opened a psc file so I wouldn't know where to begin, but I don't think it's at fault.
I've used spell research for a long time and never ran into any issues.

**Comment by CdysRed** [comment] 2022-02-14 11:41
The way I understand it, this might be because the patcher wants to edit the same book two separate ways. One in the way of _SR_ImportSkyrim.psc, and the other by SRMysticism.psc and can't overwrite itself, if that makes sense?
That's my guess anyway.

**Comment by gutieashl** [comment] 2022-02-14 11:50
Something like that. SRMysticism has a bunch of spells that remove archetypes and then add different archetypes, looks like that breaks things for some reason. Ill see if I can make a fix sometime soon.

**Comment by CdysRed** [comment] 2022-02-14 11:51
Godsend. Thank you!

Edit: Just noticed research compedium redux got an update just recently. Will test out if the mysticism patch there was fixed. Maybe save you the trouble of patching SRMysticism.

Edit2: Yup, seems to be working. At least that which I know for sure wasn't before. Feels really silly now knowing this all could've been avoided if I just checked for updates. Sorry to waste your time, and thanks again, truly.

**Comment by gutieashl** [comment] 2022-02-16 04:22
The issue should be fixed now. Should be a bit more robust dealing with overrides. Closing this issue, re-open if it happens again.

**Closed as completed** 2022-02-16 04:22 UTC

**Comment by audrius-frankonis** [comment] 2022-03-04 23:00
I'm running into the CTD problem too, I'm afraid.

Trying to set up the patch for a larger load order, but it reproduces itself in a testing profile as well.
Running the patcher, then adding a Flames spell tome ( 0009cd51 ) to my inventory via console and trying to open the inventory causes an instant crash to desktop (doing this in the LAL starter cell.)
SSEdit shows the alterations to the tomes just fine, and the crash happens whether I'm using the ESP from the BSA version or the loose files version of the patch compendium. The premade ZPatches from the compendium work without any issue I can see.
The description mentions needing to copy the textures from the Spell Experience Book's BSA to the textures folder - that's done, the textures are in the Spell Experience Book Textures For ZPatcher mod and MO2 shows them in the path the description mentions.
https://modwat.ch/u/audriuska12
Crash log: https://drive.google.com/file/d/14yAkijZ_xSy6yymr0UklSAzt4KClebPz/view?usp=sharing
The only interesting thing I can see is the "Access violation - no RTTI data!" error in the crash log. From what little I can Google up, that seems like a potential mesh issue?
